# Generated by Django 5.2.7 on 2026-05-07 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('groups', 'Fase de Grupos'), ('r32', 'Ronda de 32'), ('r16', 'Ronda de 16'), ('qf', 'Cuartos de Final'), ('sf', 'Semifinales'), ('final', 'Final')], max_length=10, unique=True, verbose_name='Código de ronda')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Orden')),
                ('base_points', models.IntegerField(default=10, verbose_name='Puntos base por acierto')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ronda activa (visible para predicciones)')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Predicciones cerradas')),
            ],
            options={
                'verbose_name': 'Ronda',
                'verbose_name_plural': 'Rondas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('confederation', models.CharField(choices=[('UEFA', 'UEFA - Europa'), ('CONMEBOL', 'CONMEBOL - Sudamérica'), ('AFC', 'AFC - Asia'), ('CAF', 'CAF - África'), ('CONCACAF', 'CONCACAF - Norte/Centro América'), ('OFC', 'OFC - Oceanía')], max_length=10, verbose_name='Confederación')),
                ('fifa_ranking', models.IntegerField(verbose_name='Ranking FIFA')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji bandera')),
            ],
            options={
                'verbose_name': 'Selección',
                'verbose_name_plural': 'Selecciones',
                'ordering': ['fifa_ranking'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField(verbose_name='Número de partido')),
                ('match_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del partido')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descripción (ej: Ganador Grupo A)')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.round', verbose_name='Ronda')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team1', to='tournament.team', verbose_name='Equipo 1')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team2', to='tournament.team', verbose_name='Equipo 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournament.team', verbose_name='Ganador real')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['round__order', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=1, unique=True, verbose_name='Grupo')),
                ('teams', models.ManyToManyField(related_name='groups', to='tournament.team', verbose_name='Equipos')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnockoutPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Puntos ganados')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='¿Acertó?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_predictions', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tournament.match')),
                ('predicted_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_wins', to='tournament.team', verbose_name='Ganador predicho')),
            ],
            options={
                'verbose_name': 'Predicción eliminatoria',
                'verbose_name_plural': 'Predicciones eliminatorias',
                'unique_together': {('user', 'match')},
            },
        ),
        migrations.CreateModel(
            name='GroupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Posición final (1-4)')),
                ('is_advancing', models.BooleanField(default=False, verbose_name='¿Avanza a siguiente ronda?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournament.group', verbose_name='Grupo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_results', to='tournament.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Resultado de grupo',
                'verbose_name_plural': 'Resultados de grupos',
                'ordering': ['group__name', 'position'],
                'unique_together': {('group', 'team')},
            },
        ),
        migrations.CreateModel(
            name='GroupPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Puntos ganados')),
                ('is_scored', models.BooleanField(default=False, verbose_name='Ya se calcularon puntos')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tournament.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_predictions', to=settings.AUTH_USER_MODEL)),
                ('predicted_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_first', to='tournament.team', verbose_name='Predicción 1° lugar')),
                ('predicted_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_second', to='tournament.team', verbose_name='Predicción 2° lugar')),
            ],
            options={
                'verbose_name': 'Predicción de grupo',
                'verbose_name_plural': 'Predicciones de grupos',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
