# Generated by Django 5.2.7 on 2026-05-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprediction',
            name='bet_credits',
            field=models.IntegerField(default=0, verbose_name='Créditos apostados'),
        ),
        migrations.AddField(
            model_name='groupprediction',
            name='credits_won',
            field=models.IntegerField(default=0, verbose_name='Créditos ganados/perdidos'),
        ),
        migrations.AddField(
            model_name='knockoutprediction',
            name='bet_credits',
            field=models.IntegerField(default=0, verbose_name='Créditos apostados'),
        ),
        migrations.AddField(
            model_name='knockoutprediction',
            name='credits_won',
            field=models.IntegerField(default=0, verbose_name='Créditos ganados/perdidos'),
        ),
        migrations.AddField(
            model_name='team',
            name='iso2_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código ISO2 (bandera)'),
        ),
    ]
