# Generated by Django 4.2.30 on 2026-05-07 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0002_groupprediction_bet_credits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del paquete')),
                ('cop_price', models.PositiveIntegerField(verbose_name='Precio en COP')),
                ('credits_amount', models.PositiveIntegerField(verbose_name='Créditos base')),
                ('bonus_credits', models.PositiveIntegerField(default=0, verbose_name='Créditos extra (bonus)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Paquete de créditos',
                'verbose_name_plural': 'Paquetes de créditos',
                'ordering': ['order', 'cop_price'],
            },
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_applied', models.PositiveIntegerField(verbose_name='Créditos aplicados')),
                ('cop_paid', models.PositiveIntegerField(verbose_name='Valor pagado en COP')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='completed', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='tournament.creditpackage', verbose_name='Paquete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra de créditos',
                'verbose_name_plural': 'Compras de créditos',
                'ordering': ['-created_at'],
            },
        ),
    ]
