# Generated by Django 4.2.30 on 2026-05-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_credit_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpurchase',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=60, verbose_name='ID Pago MP'),
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Preferencia MP'),
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=10, verbose_name='Estado'),
        ),
    ]
