# Generated by Django 4.2.30 on 2026-05-07 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_mp_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprediction',
            name='predicted_third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_third', to='tournament.team', verbose_name='Predicción 3° lugar'),
        ),
        migrations.AddField(
            model_name='groupprediction',
            name='predicted_third_advances',
            field=models.BooleanField(default=False, verbose_name='¿Predice que el 3° clasifica como mejor tercero?'),
        ),
    ]
