# Generated by Django 4.2.30 on 2026-05-08 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_groupprediction_third'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpackage',
            name='requires_round',
            field=models.ForeignKey(blank=True, help_text='Si se configura, este paquete solo se compra cuando esa ronda esté activa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_by_packages', to='tournament.round', verbose_name='Disponible desde (ronda)'),
        ),
    ]
