# Generated by Django 4.2.30 on 2026-05-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_creditpackage_requires_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generate', 'Generar datos'), ('reset', 'Resetear datos')], max_length=10, verbose_name='Acción')),
                ('n_users', models.IntegerField(default=0, verbose_name='Usuarios generados')),
                ('notes', models.TextField(blank=True, verbose_name='Notas / estadísticas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Log Sandbox',
                'verbose_name_plural': 'Área de Pruebas',
                'ordering': ['-created_at'],
            },
        ),
    ]
