# Generated by Django 4.2.30 on 2026-05-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_sandboxlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutprediction',
            name='boost_applied',
            field=models.BooleanField(default=False, verbose_name='Potenciador aplicado'),
        ),
    ]
