# Generated by Django 5.2.7 on 2026-05-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=1000, verbose_name='Créditos'),
        ),
    ]
