# Generated by Django 4.2.30 on 2026-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_credits_default_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='underdog_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplicador automático asignado al inicio de eliminatorias para usuarios bajo el promedio de grupos.', verbose_name='Multiplicador underdog'),
        ),
    ]
