# Generated by Django 4.2.30 on 2026-05-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_underdog_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='underdog_boost_uses',
            field=models.IntegerField(default=0, help_text='Cantidad de partidos en los que puede activar el potenciador underdog.', verbose_name='Usos de potenciador'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='underdog_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplicador aplicable a partidos elegidos por el usuario.', verbose_name='Multiplicador underdog'),
        ),
    ]
