# Generated by Django 4.2.30 on 2026-05-18 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_userprofile_promo_code_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positivo = ingreso, negativo = egreso')),
                ('reason', models.CharField(choices=[('referral_signup_referrer', 'Referido se registró (tú invitaste)'), ('referral_signup_referred', 'Te registraste con código de referido'), ('referral_friend', 'Tu referido invitó a alguien'), ('purchase', 'Compra de créditos'), ('prediction_win', 'Predicción acertada'), ('admin', 'Ajuste administrativo'), ('other', 'Otro')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de créditos',
                'verbose_name_plural': 'Transacciones de créditos',
                'ordering': ['-created_at'],
            },
        ),
    ]
